### Imports

In [1]:
import pandas as pd
import numpy as np
import os

### Run on individual file

In [2]:
df = pd.read_csv('../verbose_dssp_csv/(5)_1i3n.csv')
df.head()

--2  --1  -0  -1  -2  A-2  A-1  A0  A1  A2 ...  y-2  y-1  y0  y1  y2  z-2  \
0    1    1   0   0   0    0    0   1   0   0 ...    0    0   0   0   0    0   
1    1    0   0   0   0    0    1   0   0   0 ...    0    0   0   0   0    0   
2    0    0   0   0   0    1    0   0   0   0 ...    0    0   0   0   0    0   
3    0    0   0   0   0    0    0   0   0   0 ...    0    0   0   0   0    0   
4    0    0   0   0   0    0    0   0   0   0 ...    0    0   0   0   0    0   

   z-1  z0  z1  z2  
0    0   0   0   0  
1    0   0   0   0  
2    0   0   0   0  
3    0   0   0   0  
4    0   0   0   0  

[5 rows x 240 columns]

In [21]:
aas = [aa[0] for aa in df.columns.values[::5]]
print aas

['-', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [22]:
len(aas)

48

In [36]:
# what the entries of the reshaped data look like
df.columns.values.reshape(len(aas), 5)

array([['--2', '--1', '-0', '-1', '-2'],
       ['A-2', 'A-1', 'A0', 'A1', 'A2'],
       ['C-2', 'C-1', 'C0', 'C1', 'C2'],
       ['D-2', 'D-1', 'D0', 'D1', 'D2'],
       ['E-2', 'E-1', 'E0', 'E1', 'E2'],
       ['F-2', 'F-1', 'F0', 'F1', 'F2'],
       ['G-2', 'G-1', 'G0', 'G1', 'G2'],
       ['H-2', 'H-1', 'H0', 'H1', 'H2'],
       ['I-2', 'I-1', 'I0', 'I1', 'I2'],
       ['K-2', 'K-1', 'K0', 'K1', 'K2'],
       ['L-2', 'L-1', 'L0', 'L1', 'L2'],
       ['M-2', 'M-1', 'M0', 'M1', 'M2'],
       ['N-2', 'N-1', 'N0', 'N1', 'N2'],
       ['P-2', 'P-1', 'P0', 'P1', 'P2'],
       ['Q-2', 'Q-1', 'Q0', 'Q1', 'Q2'],
       ['R-2', 'R-1', 'R0', 'R1', 'R2'],
       ['S-2', 'S-1', 'S0', 'S1', 'S2'],
       ['T-2', 'T-1', 'T0', 'T1', 'T2'],
       ['V-2', 'V-1', 'V0', 'V1', 'V2'],
       ['W-2', 'W-1', 'W0', 'W1', 'W2'],
       ['X-2', 'X-1', 'X0', 'X1', 'X2'],
       ['Y-2', 'Y-1', 'Y0', 'Y1', 'Y2'],
       ['a-2', 'a-1', 'a0', 'a1', 'a2'],
       ['b-2', 'b-1', 'b0', 'b1', 'b2'],
       ['c-2', '

In [37]:
ex0 = df.ix[0].values.reshape(len(aas), 5)
ex0

array([[1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0,

In [33]:
mu = ex0.mean()
mu

0.020833333333333332

In [34]:
sigma = ex0.std()
sigma

0.14282613750835504

In [35]:
# example of scaling the amino-image
(ex0-mu)/sigma

array([[ 6.8556546 ,  6.8556546 , -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499,  6.8556546 , -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499,  6.8556546 , -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499,  6.8556546 ],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
       [-0.14586499, -0.14586499, -0.1

In [41]:
# what this amino acid is represented as
ex0_df = pd.DataFrame(ex0.T, columns=aas, index=range(-2, 3))
ex0_df.head()

-  A  C  D  E  F  G  H  I  K ...  q  r  s  t  u  v  w  x  y  z
-2  1  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
-1  1  0  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  1  0  0  0  0  0 ...  0  0  0  0  0  0  0  0  0  0
 2  0  0  0  0  0  0  0  0  0  1 ...  0  0  0  0  0  0  0  0  0  0

[5 rows x 48 columns]

In [16]:
# whole thing reshaped?
m, n = df.shape
print m, n

692 240


In [14]:
prot = df.values.reshape(m, n/5, 5)

In [17]:
prot[0]

array([[1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0,

In [18]:
prot.shape

(692, 48, 5)

### Now over all files, saving as .npy 

In [30]:
from __future__ import print_function

In [31]:
topdir, _, files = next(os.walk('../verbose_dssp_csv/'))
print(files[:5])

['(11)_1a3n.csv', '(11)_1b3n.csv', '(11)_1c3n.csv', '(11)_1d3n.csv', '(11)_1g3n.csv']


In [46]:
files[0][:files[0].index('.')]

'(11)_1a3n'

In [47]:
n = len(files)

for i, fi in enumerate(files):
    # calculate fraction of total
    per = int((i+1)*100.0/n)
    
    # print progress
    print('\rprogress: '+str(per)+'%', end='')
    
    # get window spacing
    w = int(fi[fi.find('(') + 1: fi.find(')')])
    
    # get the data
    df = pd.read_csv(topdir+fi)
    data = df.values
    
    # get dimensions
    num_r, num_c = data.shape
    
    # create the tensor
    data = data.reshape(num_r, num_c/w, w)
    
    # protein id
    p_id = fi[:fi.index('.')]
    
    # make filename for raw tensor
    fn = '../tensor_dssp_npy/' + p_id + '.npy'
    
    # finally, save the raw tensor
    np.save(fn, data)
    
    # calculate mean and std
    mu = data.mean()
    sigma = data.std()
    
    # scale
    data = (data-mu)/sigma
    
    # save the scaled tensor
    fn = '../scaled_tensor_dssp_npy/' + p_id + '.npy'
    np.save(fn, data)

progress: 100%

In [50]:
tensor_ex = np.load('../scaled_tensor_dssp_npy/(5)_1i3n.npy')
tensor_ex

array([[[ 6.8556546 ,  6.8556546 , -0.14586499, -0.14586499, -0.14586499],
        [-0.14586499, -0.14586499,  6.8556546 , -0.14586499, -0.14586499],
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
        ..., 
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499]],

       [[ 6.8556546 , -0.14586499, -0.14586499, -0.14586499, -0.14586499],
        [-0.14586499,  6.8556546 , -0.14586499, -0.14586499, -0.14586499],
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
        ..., 
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499],
        [-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.14586499]],

       [[-0.14586499, -0.14586499, -0.14586499, -0.14586499, -0.1458

In [53]:
pd.DataFrame(tensor_ex[0], columns=range(-2, 3), index=aas).head(10)

-2        -1         0         1         2
-  6.855655  6.855655 -0.145865 -0.145865 -0.145865
A -0.145865 -0.145865  6.855655 -0.145865 -0.145865
C -0.145865 -0.145865 -0.145865 -0.145865 -0.145865
D -0.145865 -0.145865 -0.145865 -0.145865 -0.145865
E -0.145865 -0.145865 -0.145865  6.855655 -0.145865
F -0.145865 -0.145865 -0.145865 -0.145865 -0.145865
G -0.145865 -0.145865 -0.145865 -0.145865 -0.145865
H -0.145865 -0.145865 -0.145865 -0.145865 -0.145865
I -0.145865 -0.145865 -0.145865 -0.145865 -0.145865
K -0.145865 -0.145865 -0.145865 -0.145865  6.855655